# Generated by Django 2.1.4 on 2019-06-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('agency_id', models.AutoField(db_column='Agency_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('e_mail', models.CharField(db_column='E-mail', max_length=45)),
                ('commercial_id', models.CharField(max_length=45)),
                ('bio', models.CharField(max_length=45)),
                ('promo_code', models.CharField(db_column='promo-code', max_length=45)),
                ('rate', models.CharField(db_column='Rate', max_length=45)),
                ('photo_url', models.TextField(db_column='photo_URL')),
            ],
            options={
                'db_table': 'Agencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('city', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(db_column='Vote_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('description', models.TextField(db_column='Description')),
            ],
            options={
                'db_table': 'Vote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('vote', models.ForeignKey(db_column='Vote_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='votes.Vote')),
                ('interested', models.IntegerField(db_column='Interested')),
                ('not_interested', models.IntegerField(db_column='Not_Interested')),
            ],
            options={
                'db_table': 'Response',
                'managed': False,
            },
        ),
    ]
