# Generated by Django 2.2.2 on 2019-06-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agencies',
            table='Agencies',
        ),
        migrations.AlterModelTable(
            name='follows',
            table='Follows',
        ),
        migrations.AlterModelTable(
            name='tripphotos',
            table="Trip_photos'",
        ),
        migrations.AlterModelTable(
            name='trips',
            table='Trips',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='Vote',
        ),
    ]
