# Generated by Django 2.1.4 on 2019-06-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('agency_id', models.AutoField(db_column='Agency_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('e_mail', models.CharField(db_column='E-mail', max_length=45)),
                ('commercial_id', models.CharField(max_length=45)),
                ('bio', models.CharField(max_length=45)),
                ('promo_code', models.CharField(db_column='promo-code', max_length=45)),
                ('rate', models.CharField(db_column='Rate', max_length=45)),
                ('photo_url', models.TextField(db_column='photo_URL')),
            ],
            options={
                'db_table': 'agencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('agency', models.ForeignKey(db_column='Agency_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='agencies.Agencies')),
                ('phone', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'phones',
                'managed': False,
            },
        ),
    ]
