# Generated by Django 2.2.2 on 2019-06-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_follows_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.AutoField(db_column='Trip_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('from_location', models.CharField(db_column='From_Location', max_length=45)),
                ('to_location', models.CharField(db_column='To_Location', max_length=45)),
                ('date_from', models.DateTimeField(db_column='Date_From')),
                ('date_to', models.DateTimeField(db_column='Date_To')),
                ('deadline', models.DateTimeField(db_column='Deadline')),
                ('meals', models.CharField(db_column='Meals', max_length=45)),
                ('price', models.FloatField(db_column='Price')),
                ('description', models.TextField(db_column='Description')),
                ('views', models.PositiveIntegerField(db_column='Views')),
                ('rate', models.FloatField(db_column='Rate')),
            ],
            options={
                'db_table': 'trips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripPhotos',
            fields=[
                ('trip', models.ForeignKey(db_column='Trip_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='agencies.Trips')),
                ('url', models.TextField(db_column='URL')),
            ],
            options={
                'db_table': "trip_photos'",
                'managed': False,
            },
        ),
    ]
