# Generated by Django 2.2.2 on 2019-06-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_tripphotos_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(db_column='Activity_id', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='Type', max_length=10)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
    ]
