# Generated by Django 2.2.2 on 2019-06-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
