# Generated by Django 2.2.2 on 2019-06-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_goingto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripphotos',
            name='trip',
        ),
        migrations.DeleteModel(
            name='GoingTo',
        ),
        migrations.DeleteModel(
            name='TripPhotos',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
