# Generated by Django 2.2.2 on 2019-06-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agencies',
            table='Agencies',
        ),
        migrations.AlterModelTable(
            name='trips',
            table='Trips',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
