# Generated by Django 2.2.2 on 2019-06-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190627_1206'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follows',
            table='Follows',
        ),
    ]
