# Generated by Django 2.2.2 on 2019-06-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(db_column='Activity_id', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='Type', max_length=10)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('agency_id', models.AutoField(db_column='Agency_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('e_mail', models.CharField(db_column='E-mail', max_length=45)),
                ('commercial_id', models.CharField(max_length=45)),
                ('bio', models.CharField(max_length=45)),
                ('promo_code', models.CharField(db_column='promo-code', max_length=45)),
                ('rate', models.CharField(db_column='Rate', max_length=45)),
                ('photo_url', models.TextField(db_column='photo_URL')),
            ],
            options={
                'db_table': 'Agencies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.AutoField(db_column='Trip_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('from_location', models.CharField(db_column='From_Location', max_length=45)),
                ('to_location', models.CharField(db_column='To_Location', max_length=45)),
                ('date_from', models.DateTimeField(db_column='Date_From')),
                ('date_to', models.DateTimeField(db_column='Date_To')),
                ('deadline', models.DateTimeField(db_column='Deadline')),
                ('meals', models.CharField(db_column='Meals', max_length=45)),
                ('price', models.FloatField(db_column='Price')),
                ('description', models.TextField(db_column='Description')),
                ('views', models.PositiveIntegerField(db_column='Views')),
                ('rate', models.FloatField(db_column='Rate')),
            ],
            options={
                'db_table': 'Trips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('city', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripPhotos',
            fields=[
                ('trip', models.ForeignKey(db_column='Trip_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='trips.Trips')),
                ('url', models.TextField(db_column='URL')),
            ],
            options={
                'db_table': "Trip_Photos'",
                'managed': False,
            },
        ),
    ]
