# Generated by Django 2.2.2 on 2019-06-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoingTo',
            fields=[
                ('user', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='trips.Users')),
            ],
            options={
                'db_table': 'going_to',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
