# Generated by Django 2.1.4 on 2019-06-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('city', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
