# Generated by Django 2.1.4 on 2019-06-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(db_column='Vote_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('description', models.TextField(db_column='Description')),
                ('photo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vote',
                'managed': False,
            },
        ),
    ]
